// packages/ui-react/src/components/CardDescription.tsx
import { cn, cvm } from '@ssword/utils-dom';
import { forwardRef } from 'react';
import { ClassProps, PropType, RefType, VariantProps } from './types';

const base = 'div';

type ComponentBase = typeof base;

const cardDescriptionVM = cvm('text-muted-foreground text-sm', {
	variants: {},
	defaultVariants: {},
	compoundVariants: [],
});

interface CardDescriptionProps
	extends PropType<ComponentBase>,
		ClassProps,
		VariantProps<typeof cardDescriptionVM> {}

const CardDescription = forwardRef<RefType<ComponentBase>, CardDescriptionProps>(
	(props, forwardedRef) => {
		const { className, ...intrinsicProps } = props;
		const Comp = base;

		return (
			<Comp
				{...intrinsicProps}
				className={cn(cardDescriptionVM({}), className)}
				ref={forwardedRef}
			/>
		);
	},
);

export default CardDescription;
export type { CardDescriptionProps as Props };

// packages/ui-react/src/components/composite/CardDescription.tsx
import { cn, cvm, type InferVariantPropsWithClass } from '@ssword/utils-dom';
import { ComponentDeclaration, defineComponent, properties } from './utils';

const cardDescriptionVM = cvm('text-muted-foreground text-sm', {
	variants: {},
	defaultVariants: {},
	compoundVariants: [],
});

const CardDescriptionComponentDeclaration = {
	is: 'div',
	variantManager: cardDescriptionVM,
	properties: properties<{}>(),
	variantProps(props) {
		return [{}, props] as const;
	},
} satisfies ComponentDeclaration;

const CardDescription = defineComponent(CardDescriptionComponentDeclaration);

export default CardDescription;
