// packages/ui-react/src/components/CardContent.tsx
import { cn, cvm } from '@ssword/utils-dom';
import { PropType, RefType, WithClass, WithVariants } from './types';
import { forwardRef } from 'react';

const base = 'div';

type ComponentBase = typeof base;

const cardContentVM = cvm(cn('px-6 flex-grow'), {
	variants: {},
	defaultVariants: {},
	compoundVariants: [],
});

interface CardContentProps
	extends WithVariants<WithClass<PropType<ComponentBase>>, typeof cardContentVM> {}

const CardContent = forwardRef<RefType<ComponentBase>, CardContentProps>((props, forwardedRef) => {
	const Comp = base;
	const { ...baseProps } = props;

	return (
		<Comp
			{...baseProps}
			ref={forwardedRef}
		/>
	);
});

export default CardContent;

// packages/ui-react/src/components/composite/ui/CardContent.tsx
import { cvm, cn, type InferVariantPropsWithClass } from '@ssword/utils';
import { defineComponent } from 'vue';

const cardContentVariant = cvm(cn('px-6 flex-grow'), {
	variants: {},
	defaultVariants: {},
	compoundVariants: [],
});

const CardContent = defineComponent<InferVariantPropsWithClass<typeof cardContentVariant>>({
	name: 'CardContent',

	props: cardContentVariant.vuePropsWithClass(),

	setup({ class: className, ...props }, { slots, attrs }) {
		return () => (
			<div
				class={cn(cardContentVariant(props), className)}
				{...attrs}
			>
				{slots.default?.()}
			</div>
		);
	},
});

export default CardContent;
