// packages/ui-react/src/components/composite/CardContent.tsx
import { cn, cvm, type InferVariantPropsWithClass } from '@ssword/utils-dom';
import { ComponentDeclaration, defineComponent, properties } from './utils';

const cardContentVM = cvm(cn('px-6 flex-grow'), {
	variants: {},
	defaultVariants: {},
	compoundVariants: [],
});

const CardContentComponentDeclaration = {
	is: 'div',
	variantManager: cardContentVM,
	properties: properties<{}>(),
	variantProps(props) {
		return [{}, props] as const;
	},
} satisfies ComponentDeclaration;

const CardContent = defineComponent(CardContentComponentDeclaration);

export default CardContent;

// packages/ui-react/src/components/CardContent.tsx
import { cn, cvm } from '@ssword/utils-dom';
import { ClassProps, Props, RefType, VariantProps } from './types';
import { forwardRef } from 'react';

const base = 'div';

type ComponentBase = typeof base;

const cardContentVM = cvm('px-6 flex-grow', {
	variants: {},
	defaultVariants: {},
	compoundVariants: [],
});

interface CardContentProps
	extends Props<ComponentBase>,
		ClassProps,
		VariantProps<typeof cardContentVM> {}

const CardContent = forwardRef<RefType<ComponentBase>, CardContentProps>((props, forwardedRef) => {
	const Comp = base;
	const { className, ...baseProps } = props;

	return (
		<Comp
			{...baseProps}
			className={cn(cardContentVM({}), className)}
			ref={forwardedRef}
		/>
	);
});

export default CardContent;
export type { CardContentProps as Props };
