// packages/ui-vue/src/components/composite/ui/Card.tsx
import { cn, cvm, type InferVariantPropsWithClass } from '@ssword/utils';
import { defineComponent, type DefineComponent } from 'vue';

const cardVariant = cvm(
	'bg-surface text-text flex flex-col gap-6 rounded-xl border px-3 py-6 shadow-sm',
	{
		variants: {
			borderAccent: {
				none: '',
				primary: 'hover:border-primary',
				secondary: 'hover:border-secondary',
			},

			transition: {
				all: 'transition-all',
				colors: 'transition-colors',
				opacity: 'transition-opacity',
				shadow: 'transition-shadow',
				transform: 'transition-transform',
				none: '',
			},
		},
		defaultVariants: {
			borderAccent: 'none',
			transition: 'none',
		},
		compoundVariants: [],
	},
);

type CardProps = InferVariantPropsWithClass<typeof cardVariant>;

const Card: DefineComponent<CardProps> = defineComponent<CardProps>({
	name: 'Card',

	props: cardVariant.vuePropsWithClass(),

	setup({ class: className, ...props }, { slots, attrs }) {
		return () => (
			<div
				class={cn(cardVariant(props), className)}
				role="presentation"
				{...attrs}
			>
				{slots.default?.()}
			</div>
		);
	},
}) as DefineComponent<CardProps>;

export default Card;
export { type CardProps };

// packages/ui-react/src/components/Card.tsx
import { cn, cvm } from '@ssword/utils-dom';
import { forwardRef } from 'react';
import { ClassProps, Props, RefType, VariantProps } from './types';

const base = 'div';

type ComponentBase = typeof base;

const cardVM = cvm(
	'bg-surface text-text flex flex-col gap-6 rounded-xl border px-3 py-6 shadow-sm',
	{
		variants: {
			borderAccent: {
				none: '',
				primary: 'hover:border-primary',
				secondary: 'hover:border-secondary',
			},

			transition: {
				all: 'transition-all',
				colors: 'transition-colors',
				opacity: 'transition-opacity',
				shadow: 'transition-shadow',
				transform: 'transition-transform',
				none: '',
			},
		},
		defaultVariants: {
			borderAccent: 'none',
			transition: 'none',
		},
		compoundVariants: [],
	},
);

interface CardProps extends Props<ComponentBase>, ClassProps, VariantProps<typeof cardVM> {}

const Card = forwardRef<RefType<ComponentBase>, CardProps>((props, forwardedRef) => {
	const Comp = base;
	const { borderAccent, transition, className, ...baseProps } = props;

	return (
		<Comp
			{...baseProps}
			className={cn(cardVM({ borderAccent, transition }), className)}
			ref={forwardedRef}
		/>
	);
});

export default Card;
export type { CardProps as Props };
