// packages/ui-react/src/components/composite/Card.tsx
import { cn, cvm, type InferVariantPropsWithClass } from '@ssword/utils-dom';
import { ComponentDeclaration, defineComponent, properties } from './utils';

const cardVM = cvm(
	'bg-surface text-text flex flex-col gap-6 rounded-xl border px-3 py-6 shadow-sm',
	{
		variants: {
			borderAccent: {
				none: '',
				primary: 'hover:border-primary',
				secondary: 'hover:border-secondary',
			},

			transition: {
				all: 'transition-all',
				colors: 'transition-colors',
				opacity: 'transition-opacity',
				shadow: 'transition-shadow',
				transform: 'transition-transform',
				none: '',
			},
		},
		defaultVariants: {
			borderAccent: 'none',
			transition: 'none',
		},
		compoundVariants: [],
	},
);

const CardComponentDeclaration = {
	is: 'div',
	variantManager: cardVM,
	properties: properties<{}>(),
	variantProps(props) {
		const { borderAccent, transition, ...intrinsicProps } = props;
		return [{ borderAccent, transition }, intrinsicProps] as const;
	},
} satisfies ComponentDeclaration;
const Card = defineComponent(CardComponentDeclaration);

export default Card;

// packages/ui-react/src/components/Card.tsx
import { cn, cvm } from '@ssword/utils-dom';
import { forwardRef } from 'react';
import { ClassProps, Props, RefType, VariantProps } from './types';

const base = 'div';

type ComponentBase = typeof base;

const cardVM = cvm(
	'bg-surface text-text flex flex-col gap-6 rounded-xl border px-3 py-6 shadow-sm',
	{
		variants: {
			borderAccent: {
				none: '',
				primary: 'hover:border-primary',
				secondary: 'hover:border-secondary',
			},

			transition: {
				all: 'transition-all',
				colors: 'transition-colors',
				opacity: 'transition-opacity',
				shadow: 'transition-shadow',
				transform: 'transition-transform',
				none: '',
			},
		},
		defaultVariants: {
			borderAccent: 'none',
			transition: 'none',
		},
		compoundVariants: [],
	},
);

interface CardProps extends Props<ComponentBase>, ClassProps, VariantProps<typeof cardVM> {}

const Card = forwardRef<RefType<ComponentBase>, CardProps>((props, forwardedRef) => {
	const Comp = base;
	const { borderAccent, transition, className, ...baseProps } = props;

	return (
		<Comp
			{...baseProps}
			className={cn(cardVM({ borderAccent, transition }), className)}
			ref={forwardedRef}
		/>
	);
});

export default Card;
export type { CardProps as Props };
