// packages/ui-react/src/components/primitives/display/Skeleton.tsx
import { cn, cvm, type InferVariantPropsWithClass } from '@ssword/utils-dom';
import { type ComponentDeclaration, defineComponent, properties } from './utils';

const skeletonVM = cvm('skeleton animate-skeleton-pulse', {
	variants: {},
	defaultVariants: {},
	compoundVariants: [],
});

const SkeletonComponentDeclaration = {
	is: 'span',
	variantManager: skeletonVM,
	properties: properties<{}>(),
	variantProps(props) {
		return [{}, props] as const;
	},
} satisfies ComponentDeclaration;

const Skeleton = defineComponent(SkeletonComponentDeclaration);

export default Skeleton;

// packages/ui-react/src/components/Skeleton.tsx
import { forwardRef } from 'react';
import { cn, cvm } from '@ssword/utils-dom';
import type { ClassProps, Props, RefType, VariantProps } from './types';

const base = 'span';
type BaseComponent = typeof base;

const skeletonVM = cvm('skeleton animate-skeleton-pulse', {
	variants: {},
	defaultVariants: {},
	compoundVariants: [],
});

interface SkeletonProps extends Props<BaseComponent>, ClassProps, VariantProps<typeof skeletonVM> {}

const Skeleton = forwardRef<RefType<BaseComponent>, SkeletonProps>(
	({ className, ...intrinsicProps }, forwardedRef) => {
		const Comp = base;

		return (
			<Comp
				{...intrinsicProps}
				ref={forwardedRef}
				className={cn(skeletonVM({}), className)}
			/>
		);
	},
);

export default Skeleton;
export type { SkeletonProps as Props };
