// packages/ui-vue/src/components/Button.vue
<script setup lang="ts">
	import { useAttrs } from 'vue';

	// attributes to forward.
	const attrs = useAttrs();
</script>

<template>
	<button
		class="inline-flex flex-row items-center button px-4 py-2 text-base rounded-md border text-text bg-primary border-border transition-all duration-200 ease-in-out hover:bg-accent hover:border-accent-strong hover:cursor-pointer active:scale-105 active:bg-accent active:border-accent-strong"
		v-bind="attrs"
	>
		<slot />
	</button>
</template>

<style lang="scss" scoped>
	// base button styles (idle)
	button {
		transition: all ease 0.2s;
		padding-top: 0.5rem;
		padding-bottom: 0.5rem;
		padding-left: 1rem;
		padding-right: 1rem;
		font-size: 1rem;
		color: var(--pallete-color-text);
		background-color: var(--pallete-color-primary);
		border-radius: 0.5rem;
		border: 1px var(--pallete-color-border) solid;

		// transition to preparing for user interaction.
		&:hover {
			transition: all ease 0.2s;
			background-color: var(--pallete-color-accent);
			border: 1px var(--pallete-color-accent-strong) solid;
			cursor: pointer;
		}

		// give user feedback. this usually gives
		// the users more serotonin.
		&:active {
			transition: all ease 0.2s;
			background-color: var(--pallete-color-accent);
			border: 1px var(--pallete-color-accent-strong) solid;
			transform: scale(1.05);
			box-shadow: none;
		}
	}
</style>

// packages/ui-react/src/components/primitives/composition/simple/Button.tsx
import { cn, cvm } from '@ssword/utils';
import { forwardRef } from 'react';

const buttonVM = cvm(
	'inline-flex items-center transition-all duration-200 ease-in-out px-4 py-2 text-base rounded-md border border-border bg-primary text-text hover:bg-accent hover:border-accent-strong hover:cursor-pointer active:scale-105 active:bg-accent active:border-accent-strong',
	{
		variants: {
			variant: {
				glass: 'bg-transparent backdrop-blur-md',
				primary: 'bg-primary',
			},
			size: {
				sm: 'px-3 py-1.5 text-sm',
				md: 'px-4 py-2 text-base',
				lg: 'px-6 py-3 text-lg',
				xl: 'px-8 py-4 text-xl',
			},
		},
		defaultVariants: {
			variant: 'primary',
			size: 'md',
		},
		compoundVariants: [],
	},
);

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
	variant?: 'glass' | 'primary';
	size?: 'sm' | 'md' | 'lg' | 'xl';
}

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
	({ className, variant, size, ...props }, ref) => (
		<button
			ref={ref}
			{...props}
			className={cn(buttonVM({ variant, size }), className)}
		>
			{props.children}
		</button>
	),
);
