// site/app/components/PostHeroSection.vue
<script setup lang="ts">
	const props = withDefaults(defineProps<{ swap?: boolean }>(), {
		swap: false,
	});
</script>

<template>
	<section
		:data-layout="props.swap ? 'swapped' : 'normal'"
		:class="[
			'post-hero-section min-h-screen',
			'bg-background text-text transition-colors duration-500',
			'gap-6',

			// child styles
			'*:p-4',

			// default styles
			'[&>.post-hero-section-sample]:hidden',

			// medium above
			'md:[&>.post-hero-section-sample]:block',
		]"
	>
		<slot />
	</section>
</template>

<style lang="css" scoped>
	.post-hero-section {
		display: grid;
		grid-template-rows: 1fr;
		grid-template-columns: 1fr;
		grid-template-areas: 'view-panel';
	}

	@media screen and (width >= 48rem) {
		.post-hero-section {
			grid-template-columns: 1fr 1fr;
			grid-template-rows: 1fr;
			grid-template-areas: 'view-panel sample-panel';
		}

		.post-hero-section[data-layout='swapped'] {
			grid-template-areas: 'sample-panel view-panel';
		}
	}
</style>

// apps/ui/src/components/PostHeroSection.tsx
import { cn } from '@ssword/utils-dom';
import { FC, PropsWithChildren } from 'react';

const PostHeroSection: FC<
	PropsWithChildren<{ swap?: boolean; className?: string; id?: string }>
> = ({ children, swap = false, className = '', id }) => (
	<section
		id={id}
		data-layout={swap ? 'swapped' : 'normal'}
		className={cn([
			'post-hero-section min-h-screen',
			'bg-background text-text transition-colors duration-500',
			'gap-6',

			// child styles
			'*:p-4',

			// default styles
			'grid grid-cols-[1fr] grid-rows-[1fr] md:[grid-template-areas:"view-panel_sample-panel"] md:data-[layout="swapped"]:[grid-template-areas:"sample-panel_view-panel"] [&>.post-hero-section-sample]:hidden',

			// medium above
			'md:[&>.post-hero-section-sample]:block',

			className,
		])}
	>
		{children}
	</section>
);

export default PostHeroSection;
