// packages/ui-react/src/components/CardDescription.tsx
import { cvm } from '@ssword/utils-dom';
import { forwardRef } from 'react';
import { PropType, RefType, WithClass, WithVariants } from './types';

const base = 'div';

type ComponentBase = typeof base;

const cardDescriptionVM = cvm('text-muted-foreground text-sm', {
	variants: {},
	defaultVariants: {},
	compoundVariants: [],
});

interface CardDescriptionProps
	extends WithVariants<WithClass<PropType<ComponentBase>>, typeof cardDescriptionVM> {}

const CardDescription = forwardRef<RefType<ComponentBase>, CardDescriptionProps>(
	(props, forwardedRef) => {
		const { ...intrinsicProps } = props;
		const Comp = base;

		return (
			<Comp
				{...intrinsicProps}
				ref={forwardedRef}
			/>
		);
	},
);

export default CardDescription;

// packages/ui-vue/src/components/composite/ui/CardDescription.tsx
import { cvm, type InferVariantPropsWithClass, cn } from '@ssword/utils';
import { defineComponent } from 'vue';

const cardDescriptionVariant = cvm('text-muted-foreground text-sm', {
	variants: {},
	defaultVariants: {},
	compoundVariants: [],
});

const CardDescription = defineComponent<InferVariantPropsWithClass<typeof cardDescriptionVariant>>({
	name: 'CardDescription',

	props: cardDescriptionVariant.vuePropsWithClass(),

	setup({ class: className, ...props }, { slots, attrs }) {
		return () => (
			<div
				class={cn(cardDescriptionVariant(props), className)}
				{...attrs}
			>
				{slots.default?.()}
			</div>
		);
	},
});

export default CardDescription;
